### PR TITLE
WEBEU4 - Build Week - Blake Lower

### PR DESCRIPTION
**Pull request by blakelower**

### CODE REVIEW

**Comment by Becheru888** [comment]
You have a good project here Blake  😄 

**What looks good** 😮 

- Semantic HTML,
- Your page is responsive, and look pretty good on mobile.
- You have mixins,
- You have variables.

**What it is to improve** 🤒 
- Your less code is not nested as it should be.
image
- Your page is not deployed. 
- You have only one variable declared but its value doesn't have any effect on the page.
- The 3 mixins which you have declared are not used anywhere in your code.

Overall your webpage looks good, but you have to replace some style with mixins and variables and work for nest your code properly as these are part of the MVP.
I will suggest you have a look at the requirements again. And give it a second try. 
Please reach out if you need any help.

Keep pushing you doing a great job! 💯

**Comment by blakelower** [comment]
so if i fix it up a bit that will be okay, but did i fail?

**Comment by Becheru888** [comment]
You have time until tomorrow 17:00 UK to fix your MVP! 🗡

**Comment by blakelower** [comment]
Okay, if i need any help i can ask you?

**Comment by Becheru888** [comment]
Do your research, go online, revisit the training kit, use the help desk/ help channel, follow the process.

**Comment by blakelower** [comment]
Okay, Remi 😀 thank you for the feedback

**Review by josenriagu — APPROVED** [review]

**Comment by josenriagu** [comment]
Awesome! you page is live NOW;
You may view it here: https://marketing-page-git-blake-lower.bwchefportfolio.now.sh/

**Pull request closed without merging**
